### ISSUE TITLE
Protected pages are protected by alien providers

### ISSUE THREAD

**Issue by dvvasilyev** [pac4j/buji-pac4j-demo#11]
Hi,
I tried to open VK/index.jsp and VK.com ask my credentials then I opened facebook/index.jsp and page was opened with VK profile, without Facebook credentials.
Opposite case works as well: logout, open Facebook protected page and next protected pages accessed by Facebook profile.

**Comment by leleuj** [comment]
This is exactly the way it works: the vk/index.jsp triggers a VK login while the facebook/index.jp triggers a Facebook login. And as soon as you're authenticated, you can access the protected URL. If you want to limit the kind of profile which can access an URL, use this authorizer: https://github.com/pac4j/pac4j/blob/master/pac4j-core/src/main/java/org/pac4j/core/authorization/authorizer/CheckProfileTypeAuthorizer.java
