### ISSUE TITLE
demo project cannot run

### ISSUE THREAD

**Issue by gtyang** [pac4j/buji-pac4j-demo#13]
There is an error raised when I run mvn compile:

[ERROR] Failed to execute goal on project buji-pac4j-demo: Could not resolve dependencies for project org.pac4j.demo:buji-pac4j-demo:war:2.2.0-SNAPSHOT: Could not find artifact io.buji:buji-pac4j:jar:2.2.0-SNAPSHOT in sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots) -> [Help 1]

**Comment by leleuj** [comment]
Strange. In any case, use the 2.1.x branch as things are a bit unstable on this one.
