### ISSUE TITLE
JWT with org.pac4j.jwt.config.signature.RSASignatureConfiguration is undocumented

### ISSUE THREAD

**Issue by minfrin** [pac4j/buji-pac4j-demo#20]
In the demo shiro.ini, we have an example configuration for the trivial SecretSignatureConfiguration case as follows:

https://github.com/pac4j/buji-pac4j-demo/blob/master/src/main/resources/shiro.ini

    signingConfig = org.pac4j.jwt.config.signature.SecretSignatureConfiguration
    signingConfig.secret = 12345678901234567890123456789012

We need a corresponding example for the RSASignatureConfiguration and ECSignatureConfiguration:

    signingConfig = org.pac4j.jwt.config.signature.RSASignatureConfiguration
    signingConfig.????? = file:/path/to/key.[pem|p12|whatever]

    signingConfig = org.pac4j.jwt.config.signature.ECSignatureConfiguration
    signingConfig.????? = file:/path/to/key.[pem|p12|whatever]

Most specifically, what is the value of ????? above?

**Comment by leleuj** [comment]
I don't think that the `RSASignatureConfiguration` and the `ECSignatureConfiguration` components can really work on Shiro as they expect keys. We certainly need some enhanced setters.

**Comment by leleuj** [comment]
I implemented a very simple solution based on JWK: https://github.com/pac4j/pac4j/commit/037ec2533a0b379fcea319fe73e21d03b2d131b1
